# Generated by Django 5.2.11 on 2026-02-23 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='career_goal',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='interests',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='weak_subjects',
            field=models.TextField(blank=True),
        ),
    ]
