# Generated by Django 5.2.11 on 2026-02-28 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
